name: Build & Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: docker build --platform=linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/human-or-ai ./server

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/human-or-ai

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          # CORRECTED: Use 'key' input for the private key
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
              # Commands to execute on your EC2 instance
              # Ensure Docker is installed and running on your EC2 instance.
              echo "Pulling latest Docker image..."
              docker pull ${{ secrets.DOCKER_USERNAME }}/human-or-ai

              echo "Stopping and removing existing container (if any)..."
              sudo docker stop human-or-ai || true # Use the --name for stopping/removing
              sudo docker rm human-or-ai || true # Using the assigned name 'human-or-ai'

              echo "Running new Docker container..."
              sudo docker run -d --name human-or-ai -p 80:8000 \
                -e API_KEY=${{ secrets.GOOGLE_API_KEY }} \
                ${{ secrets.DOCKER_USERNAME }}/human-or-ai

              echo "Deployment complete."